import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Test Job
        </h1>

        <div className={styles.grid}>
          <a href="/task-1" className={styles.card}>
            <h2>Task 1 &rarr;</h2>
          </a>
          <a href="/task-2" className={styles.card}>
            <h2>Task 2 &rarr;</h2>
          </a>
          <a
            href="/task-3"
            className={styles.card}
          >
            <h2>Task 3 &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
